### ISSUE TITLE
How to Determine which switch has been toggled

### ISSUE THREAD

**Issue by davecarlson** [Julusian/react-bootstrap-switch#1]
Take the following case:

```
<Switch data-switchId={1} onChange={::this._toggledState} state={true}  />
<Switch data-switchId={2} onChange={::this._toggledState} state={false} />

```

`onChange` only returns true or false, not which switch has been toggled.

Is there a way for it to also include the event ?

**Comment by ashby** [comment]
if you add a unique name attribute to each Switch and then console.log 'this' within your onChange event, you'll notice that you can access 'this.name' for each switch.

**Comment by Julusian** [comment]
Sorry for taking so long on this.
If the function used for onChange accepts 2 parameters, it will get (elm, newState). If only 1 is accepted it will get (newState) to maintain compatibility for others.

I hope this makes sense
