### ISSUE TITLE
switch cannot be toggled when click the "white space" part in the switch

### ISSUE THREAD

**Issue by ghost** [Julusian/react-bootstrap-switch#10]
I notice that a switch can only be toggled when you click the handle (the green circle part in below picture). If you click the white empty space, nothing happens. Anyone else notice this as well?

![image](https://cloud.githubusercontent.com/assets/1069858/13799294/10b1e2d4-eb72-11e5-988e-e608f4128ae8.png)

This is different with Bootstrap-Switch where you can toggle the switch by clicking either the handle or the "white space part". This issue is tiny but it's better to implement for a better user experience.

By the way the issue happens to me when use react-bootstrap-switch 3.4.2 in chrome and firefox.

**Comment by Julusian** [comment]
Hi @wangdanny, is the issue you are having with the css from the repo, or when using the library styled like the picture?
I have had a play with the included css and found a possible case of your issue, but it will only apply if you use this css

**Comment by loiclefloch** [comment]
@Julusian I have the same problem on Chrome and Safari. But i do not use any theme or custom css.
bootstrap-switch: v3.3.2
react-bootstrap-switch: v3.4.4

**Comment by sample-usr** [comment]
@Julusian I'm having the same issue and i'm using the included CSS with the latest version: 3.4.5.
Do you know what might be the problem?

**Comment by ghost** [comment]
Hi @Julusian sorry for the late reply. Well you are right. It looks I forgot to use the react-bootstrap switch css file and actually I am using the css of bootstrap switch (the UI just looks good except this issue). After I switching to the react-bootstrap switch css, the issue disappears. Maybe you can check with other guys who have this issue but all good to me now.

Thank you very much.

**Comment by Julusian** [comment]
@wangdanny I'm glad your issue is now resolved. There is a note in the readme which will hopefully help people in future.
@razagill Are you able to send/link an example with your issue?

**Comment by shotor** [comment]
For anyone that encounters this issue: Try running an incognito window. For me some extension was messing with it.
