### ISSUE TITLE
Breaks in react@15.0.1

### ISSUE THREAD

**Issue by Showyilu** [Julusian/react-bootstrap-switch#13]
should the peerDependencies be added as sth like
{ 
   "react": "^0.14 || ^15.0.0",
  "react-dom": "^0.14 ||  ^15.0.0"
}

**Comment by jflayhart** [comment]
`invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's`render`method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

I don't know if I will have time, but I will work on a PR if possible.

**Comment by jflayhart** [comment]
@Showyilu I took your suggestion. Submitted PR. I think multiple copies of React were running and it was confused, since React (15) is of course a dependency in my project.

**Comment by Julusian** [comment]
This has been merged in v3.4.5
I haven't been able to do any thorough testing myself, so let me know if you experience any issues.

**Comment by Showyilu** [comment]
@jflayhart @Julusian Cheers
