### ISSUE TITLE
Double clicking results in switch being stuck

### ISSUE THREAD

**Issue by adamthewan** [Julusian/react-bootstrap-switch#16]
Through testing, we found out that double clicking rapidly on the switch would cause it to freeze. We think it's because we're both changing the state and getting the state for the switch at the same time. This is our code: 

<Switch state={!this.props.q.private} onChange={this.togglePrivate.bind(this)} labelWidth={2} size="mini" offColor='danger' onText="Public" offText="Private"/>

Would like help on this issue, since I foresee that this can be a problem.

**Comment by Julusian** [comment]
Hi
It looks like you meant to attach some example code in your message, but forgot.
I have tested rapid double clicking in my projects and cannot reproduce so an example would be really helpful

**Comment by rareyman** [comment]
I'm having the same issue. I have a simple interface with two options and a simple yes/no switch. Below I have included the pertinent code for just one of the switches.

The interface works fine, but if I click the switch too quickly (double-click or just spam-click the  switch) eventually the browser window locks up and freezes. On one occasion, after a few minutes the switch began working again. I am using Chrome 52.0.2743.116

### Render

``` javascript
<div className="row">
    <div className="col-md-8">Show Help?</div>
    <div className="col-md-4">
        <Switch
                state={this.state.helpOn}
                size="mini"
                animate={false}
                onText="Yes"
                offText="No"
                labelText=""
                handleWidth="auto"
                labelWidth="auto"
                baseClass="bootstrap-switch"
                wrapperClass="switch-hide-help"
                onChange={this.getSwitchState.bind(null, 'help')}
        />
    </div>
</div>
```

### Initial State

``` javascript
getInitialState()
{
    return {
        // set initial state
        helpOn: true
    };
}
```

### Functions

``` javascript
getSwitchState(field)
{
    if (field == 'help') {
        this.setState({ helpOn: !this.state.helpOn });
    }
}
```

**Comment by Julusian** [comment]
Is this still an issue in v15.0.x?
