### ISSUE TITLE
React state based switching?

### ISSUE THREAD

**Issue by ghost** [Julusian/react-bootstrap-switch#2]
How can I make this component not visually turn on/off when clicking, and just let its on/off state be determined with the component state that I change by myself?

**Comment by ashby** [comment]
I would also really love to to know how to do this. It appears as though the switch ignores the state once state is set.

**Comment by Julusian** [comment]
There are both readonly and a disabled props for the element, that will stop it changing on click (they were broken but I have just fixed them). 
You can update the state of the element once it has been created by using the value method

Or have i misunderstood you?

**Comment by ghost** [comment]
If you have fixed readonly, then I should be able to use that. Thanks.
