### ISSUE TITLE
Switch is not rendering properly

### ISSUE THREAD

**Issue by raaone7** [Julusian/react-bootstrap-switch#23]
In my react 15 app using react-bootstrap as well, i am doing the following in one of my components

import Switch from 'react-bootstrap-switch';

using the below code in return of the component 

<Switch state="true" size="mini" animate="true" />

![image](https://cloud.githubusercontent.com/assets/10722171/16620895/877c24f2-43d7-11e6-95cb-4f7b33565819.png)

I was expecting something graphical. 
Not sure, what am i missing.  React bootstrap components are working perfect though.

**Comment by Julusian** [comment]
It looks as though you havent included the css/less into your project. these should be available through the package installed from npm

**Comment by raaone7** [comment]
Thank you very much.

Fantastic. It was silly me. included the css in the index.js by pasting below
import '../../../../node_modules/react-bootstrap-switch/dist/css/bootstrap3/react-bootstrap-switch.css';
And it resolved the issue. 

![image](https://cloud.githubusercontent.com/assets/10722171/16650665/b3d5d5ba-4482-11e6-9d62-d1da450ba12a.png)

Not sure, how to include the css in my webpack config. Treid this below , it didnt work . Any suggestions or links to make it work.

In webpack, using below, it doesn't render the toggle switch properly
          {
                test: /.css$/,
                loader: ['style', 'css'],
            include: ['src/main/resources/css/react-bootstrap-switch.css']
            }
