### ISSUE TITLE
 `NaN` is an invalid value for the `marginLeft` css style property.

### ISSUE THREAD

**Issue by astanciu** [Julusian/react-bootstrap-switch#26]
Getting this warning:

warning.js:36 Warning: `NaN` is an invalid value for the `marginLeft` css style property. Check the render method of `Switch`.

**Comment by ThomsCass** [comment]
get the same one when adding the `labelWidth={200}`property.

``` javascript
warning.js:44 Warning: `NaN` is an invalid value for the `width` css style property. 
Check the render method of `Switch`.
```

**Comment by adityamr15** [comment]
i already make PR #28 to fix this issue
