### ISSUE TITLE
incorrect rendering in v15

### ISSUE THREAD

**Issue by pdeva** [Julusian/react-bootstrap-switch#29]
upgrading from v3 to v15 results in incorrect rendering of the switch

Screenshot:
http://content.screencast.com/users/PrashantDeva/folders/Jing/media/934fc767-e3ab-4915-af48-042e2686efa1/2016-10-08_1458.png

I am including the right css.

**Comment by mkrauser** [comment]
In my case this only occurs in firefox and the reason is the off-lable-text being to wide. I fixed that with the following:

`<Switch ... handleWidth={35} labelWidth={35} />`

the value of 35 may vary depending on your on/off/label-texts

**Comment by Julusian** [comment]
Fixed in v15.0.3
