### ISSUE TITLE
How to hook a eventlistener on switch

### ISSUE THREAD

**Issue by Gfast2** [Julusian/react-bootstrap-switch#35]
Very cool stuff! 

Since I'm new in react. I'd like to know how to listen the switch toggle event?

can you give me even some example snippet?

**Comment by Gfast2** [comment]
"onChange" in API. I'll go and Figure out how to deal with it .
If I've something usefull, I'll give a pull request. ;P

**Comment by Gfast2** [comment]
Hi Julusian. I've got i ->

	<Switch onChange={(el, state) => this.handleSwitch(el, state)} 
            onColor= {this.state.swOnColor}
            bsSize = {this.state.swSize}
            onText = {this.state.swOnText}
            offText= {this.state.swOffText}
            name= 'telnet'
            />

Init your Switch in this fashion. And then in the same React class I can build the action handler for this swtich:

    handleSwitch(elem, state) {
    	console.log('handleSwitch. elem:', elem);
    	console.log(elem.state.value);
    	console.log(elem.props.name);
    }

**Comment by Julusian** [comment]
Hi, Sorry for not responsding sooner.
Did you manage to figure this out, or do you still need assistance?

**Comment by Gfast2** [comment]
Hi Julusian,
No, I don't need your help any more. You can add those snippet from me above to the readme. I think it make sense for new bee like me. :D Thanks again for your brilliant dedication 👍
