### ISSUE TITLE
animation does not work on chrome

### ISSUE THREAD

**Issue by Fr33maan** [Julusian/react-bootstrap-switch#39]
Hi,

I'm using
bootstrap-sass 3.3.7
react 15.4.1
react-bootstrap-switch 15.0.4 
react-bootstrap 0.30.7

Switch animation is working on firefox but not on chrome.

Do you need more information to reproduce ?

**Comment by Julusian** [comment]
Hi
Sorry for the delay.
Do you have an example you can share?
I am unable to reproduce this myself, so an example would be really helpful to get this fixed

**Comment by DjLeChuck** [comment]
Same here.
I'm using react-form and try to wrap the Switch:

```jsx
<Switch {...rest} id={id} 
  defaultValue={getBooleanValue(getValue(false))} 
  onChange={(el, state) => setValue(state, noTouch)} />
```

If I use `default` prop, the switch doesn't change at all. With `defaultValue` it change but without animation on Chrome (works with Firefox)

`getBooleanValue` returns a boolean: 
```js
const getBooleanValue = value => parseInt(value, 10) ? true : false;
```

**Comment by fahadbinashraf** [comment]
Hi, 
in my case it was animating first time only on chrome
after some inspections i found out that  "bootstrap-switch-animate" class was being replaced by "bootstrap-switch-focused" class which didn't had the animation style.
so i just placed the following snippet in my custom css file to get it to always work 
`
.bootstrap-switch-container {
  -webkit-transition: margin-left 0.5s;
  -o-transition: margin-left 0.5s;
  transition: margin-left 0.5s;
}
`

**Comment by Julusian** [comment]
The latest version might solve these issues, I found that if any props are changed whilst the switch should be animating it would stop animating, which looks like it could have been the cause of your issues
