### ISSUE TITLE
Select still open on click empty square on switch

### ISSUE THREAD

**Issue by danilaramaniuk2378** [Julusian/react-bootstrap-switch#41]
Please see repo https://github.com/DanilaRomaniuk/sample-for-react-switch-bug to reproduce bug

Steps to reproduce:

1) Click on select
2) Click on **white** square in switch

**AR**: Select options are shown

**ER**: Select options are hidden

**NOTE**: On click on not white empty square all works fine, In case you need I can record a video of a bug

![149267780428955](https://cloud.githubusercontent.com/assets/6383431/25221733/d69d22c4-25be-11e7-8e88-44e77110f2de.gif)

**Comment by Julusian** [comment]
I have published v3.4.6 which should resolve this issue.
