### ISSUE TITLE
Use in react-bootstrap Tabs component causes indeterminate state on tab switch

### ISSUE THREAD

**Issue by gtwilliams03** [Julusian/react-bootstrap-switch#50]
I cannot figure this out - but I am going to report it to you in case it is a bug.  I am using this awesome component in a react-bootstrap `Tabs` container (inside a `Tab` component) as follows:

```
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { Tab, Tabs } from 'react-bootstrap'
import Switch from 'react-bootstrap-switch'

class TestTabSwitch extends Component {

    constructor(props) {
        super(props)
        this.state = { tab: 1, testSwitch: false }
    }

    handleChangeTab(tab) {
        this.setState({ tab })
    }
    
    render() {
        return (
            <div>
                <Tabs activeKey={this.state.tab} onSelect={e => this.handleChangeTab(e)} id="test-switch-in-tab-container">
                    <Tab eventKey={1} title="Has a switch">
                        <Switch onText='Yes' offText='No' value={this.state.testSwitch}
                            onChange={(el, checkedState) => this.setState({ testSwitch: checkedState })} />
                    </Tab>
                    <Tab eventKey={2} title="No switch">
                        No switch
                    </Tab>
                </Tabs>                    
            </div>
        )
    }

}

export default TestTabSwitch
```

The switch renders fine on mount:

![image](https://user-images.githubusercontent.com/1564628/33058809-63a0a936-ce5f-11e7-94ab-48fc7e02a9ed.png)

However, the switch ends up in a strange indeterminate state if you switch tabs and back to the tab containing the switch:

![image](https://user-images.githubusercontent.com/1564628/33058831-8113b9cc-ce5f-11e7-8815-d1994cb5a593.png)

Any thoughts?

**Comment by gtwilliams03** [comment]
A workaround is to add `animation={false}` to the `Tabs` component and then the switches render correctly.  So it must be the fade out/in animation that the `Tabs` component uses when switching between tabs and the switches aren't rendering correctly until they are fully visible. 

This issue may be related to this problem if this helps fix it:

https://github.com/Bttstrp/bootstrap-switch/issues/376

**Comment by Rubb3r** [comment]
@gtwilliams03 
I add `mountOnEnter={true}` to the `Tabs `component

**Comment by gtwilliams03** [comment]
@Rubb3r Brilliant!  This did the trick for me.  Thank you!
